name: media_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # ... tus otros paquetes ...
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.6
  # ESTA ES LA CLAVE: 'any' fuerza a descargar el último parche antibloqueo
  youtube_explode_dart: any
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  audio_service: ^0.18.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
