workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 30
    environment:
      flutter: stable
      android_signing:
        - reference: keystore_ref # (si usas firmas, o déjalo omitido)
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/bundle/**/*.aab
