allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(':app')
}

// Inyecta el SDK 34 a todos los plugins externos (resuelve el error de package_info_plus)
subprojects { subproject ->
    afterEvaluate {
        if (subproject.hasProperty('android')) {
            subproject.android {
                compileSdkVersion 34
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

