name: Compilador Apex (Android)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extraer código fuente
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Descargar librerías
      run: flutter pub get

    - name: Compilar el APK
      run: flutter build apk --release

    - name: Subir el APK listo
      uses: actions/upload-artifact@v4
      with:
        name: Apex-VIP-App
        path: build/app/outputs/flutter-apk/app-release.apk
